# Generated by Django 3.1.7 on 2021-05-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='saddress',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='sbid',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='seller',
            name='scategory',
            field=models.CharField(choices=[('Contemporary', 'Contemporary'), ('Pop', 'Pop'), ('Impressionism', 'Impressionism'), ('Surrealism', 'Surrealism')], default='U', max_length=15),
        ),
        migrations.AddField(
            model_name='seller',
            name='semail',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='sfname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='sgender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='U', max_length=8),
        ),
        migrations.AddField(
            model_name='seller',
            name='slname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='tnc',
            field=models.BooleanField(default=False),
        ),
    ]
